<?php
/**
 * Message translations.
*
* This file is automatically generated by 'yii message/extract' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
		'Continue' => 'Kontynuuj',
		'E-mail' => '',
		'Username' => 'Nazwa u¿ytkownika',
		'Authorization' => 'Logowanie',
		'Captcha' => 'Kod captcha',
		'Check your E-mail for further instructions' => 'SprawdŸ swoj¹ skrzynkê e-mail, gdzie zosta³y wys³ane dalsze instrukcje',
		'Check your e-mail {email} for instructions to activate account' => 'SprawdŸ swoj¹ skrzynkê e-mail {email}, gdzie zosta³a wys³ana instrukcja jak aktywowaæ konto',
		'Confirm' => 'PotwierdŸ',
		'Confirm E-mail' => 'PotwierdŸ adres e-mail',
		'Could not send confirmation email' => 'Nie uda³o siê wys³aæ maila potwierdzaj¹cego',
		'E-mail confirmation for' => 'Potwierdzenie e-maila dla',
		'E-mail confirmed' => 'Adres e-mail potwierdzony',
		'E-mail is invalid' => 'Nieprawid³owy adres e-mail',
		'Forgot password ?' => 'Zapomnia³eœ has³o?',
		'Incorrect username or password.' => 'Nieprawid³owy login lub has³o',
		'Login' => 'Zaloguj',
		'Login has been taken' => 'Login jest ju¿ zajêty',
		'Password' => 'Has³o',
		'Password recovery' => 'Odzyskiwanie has³a',
		'Password reset for' => 'Resetowanie has³a dla',
		'Recover' => 'Odzyskaj',
		'Register' => 'Zarejestruj',
		'Registration' => 'Rejestracja',
		'Registration - confirm your e-mail' => 'Rejestracja - potwierdŸ swój adres e-mail',
		'Remember me' => 'Zapamiêtaj mnie',
		'Repeat password' => 'Powtórz has³o',
		'This E-mail already exists' => 'Ten e-mail ju¿ istnieje w bazie',
		'Token not found. It may be expired' => 'Klucz nie znaleziony. Móg³ skoñczyæ siê jego okres wa¿noœci.',
		'Token not found. It may be expired. Try reset password once more' => 'Klucz nie znaleziony. Móg³ skoñczyæ siê jego okres wa¿noœci. Spróbuj ponownie zresetowaæ has³o.',
		'Too many attempts' => 'Zbyt wiele prób',
		'Unable to send message for email provided' => 'Nie uda³o siê wys³aæ wiadomoœci na podany adres e-mail',
		'You could not login from this IP' => 'Nie mo¿esz siê zalogowaæ z tego IP',

		// emails:
		'Hello {username}, follow this link to reset your password:' => 'Witaj {username}, kliknij poni¿szy link aby zresetowaæ swoje has³o:',
		'Reset password' => 'Restart has³a',
		'Hello {username}, follow this link to confirm your email:' => 'Witaj {username}, kliknij poni¿szy link aby potwierdziæ swój adres email:',
		'Hello, you have been registered on {website}' => 'Witaj, zosta³eœ zarejestrowany na {website}',
		'Follow this link to confirm your E-mail and activate account:' => 'Kliknij poni¿szy link aby potwierdziæ swój adres email i aktywowaæ konto:'
];
